name: summariser-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cython
  - tensorflow==2.12.0
  - torch==2.0.1
  - pip:
    - deep-translator==1.11.1
    - emoji==2.5.1
    - Flask==2.3.2
    - Flask-Cors==3.0.10
    - malaya==5.0
    - malaya-boilerplate==0.0.24
    - metric-visualizer==0.9.9
    - numpy==1.23.5
    - pandas==2.0.2
    - protobuf==3.20.3
    - pyabsa==2.3.1
    - pypi-kenlm==0.1.20220713
    - PySastrawi==1.2.0
    - regex==2023.6.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentencepiece==0.1.99
    - spacy==3.5.3
    - spacy-alignments==0.9.0
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - spacy-lookups-data==1.0.3
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.1
    - tensorflow-addons==0.20.0
    - torchlibrosa==0.1.0
    - tqdm==4.65.0
    - transformers==4.30.2
    - Unidecode==1.3.6
    - youtokentome==1.0.6